# Configuration file version
apiVersion: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  - name: Alertmanager
    type: alertmanager
    url: http://localhost:9093
  - name: Prometheus
    type: prometheus
    url: http://localhost:9090