{
 "title": "Sensor Dashboard",
 "description": "Time Series graphs for 3 demo sensors",
 "tags": [ "sensor" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource_var", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "All Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iot_air_temperature_fahrenheit", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iot_air_humidity_percent", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Bedroom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Bedroom Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "iot_air_heat_index_fahrenheit{job=\"sensor1\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Bedroom Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "iot_air_humidity_percent{job=\"sensor1\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Sunroom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Sunroom Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "iot_air_temperature_fahrenheit{job=\"sensor2\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Sunroom Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "iot_air_humidity_percent{job=\"sensor2\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Basement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Basement Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "iot_air_temperature_fahrenheit{job=\"sensor3\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Basement Humidity",
   "type": "timeseries",
   "description": "Basement humidity and temperature ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "iot_air_humidity_percent{job=\"sensor3\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}