# rules for raspberry pi alerts

groups:
  - name: zero-rules
    rules:

      - alert: NodeDown
        expr: up == 0
        for: 5m
        annotations:
          summary: "{{ $labels.job }}  is down"
          description: "{{ $labels.job }}  is down for more than 5 minutes"

      - record: job:node_memory_Mem_bytes:available
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100

      - alert: NodeMemoryUsageAbove75%
        expr: (100 - job:node_memory_Mem_bytes:available) >= 75
        for: 2m
        annotations:
          summary: "Raspberry Pi node memory usage is very HIGH"
          description: "Raspberry Pi node memory for instance {{ $labels.instance }} has reached {{ $value }}%"

      - alert: NodeCPUUsageHigh
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
        for: 2m
        annotations:
          summary: "Raspberry Pi CPU usage is HIGH"
          description: "Raspberry Pi CPU load for instance {{ $labels.instance }} has reached {{ $value }}%"

      - alert: NodeFreeDiskSpaceLess30%
        expr: (sum by (instance) (node_filesystem_free_bytes) / sum by (instance) (node_filesystem_size_bytes)) * 100 < 30
        for: 2m
        annotations:
          summary: "Raspberry Pi node free disk space is running out"
          description: "Raspberry Pi node disk is going to full (< 30% left)\n  Current free disk space is {{ $value }}"

      - alert: NodeFreeDiskSpaceLess20%
        expr: (sum by (instance) (node_filesystem_free_bytes) / sum by (instance) (node_filesystem_size_bytes)) * 100 < 20
        for: 2m
        annotations:
          summary: "Raspberry Pi node free disk space is running out"
          description: "Raspberry Pi node disk is going to full (< 20% left)\n  Current free disk space is {{ $value }}"