global:
  scrape_interval: 30s
  evaluation_interval: 30s
rule_files:
  - /etc/prometheus/rules/node-rules.yml
  - /etc/prometheus/rules/sensor-rules.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: grafana
    static_configs:
      - targets:
          - localhost:3000
  - job_name: alertmanager
    static_configs:
      - targets:
          - localhost:9093
  - job_name: sunroom
    static_configs:
      - targets:
          - 192.168.1.15:80
        labels:
          location: 'outside'
  - job_name: bedroom
    static_configs:
      - targets:
          - 192.168.1.16:80
        labels:
          location: 'inside'
  - job_name: basement
    static_configs:
      - targets:
          - 192.168.1.17:80
        labels:
          location: 'inside'